export class Users {
    id: string = '';
    userOrganization: string = '';
    employeeType: string = '';
    commonName: string = '';
    loginID: string = '';
    firstName: string = '';
    lastName: string = '';
    fullName: string = '';
    title: string = '';
    email: string = '';
    businessPhone: string = '';
    managerEmail: string = '';
    description: string = '';
    address: string = '';
    street: string = '';
    city: string = '';
    state: string = '';
    postalCode: string = '';
    status: string = '';
}